### PR TITLE
BD-1261: Hidden endpoint doc for GET App Group Apps

### PR DESCRIPTION
**Pull request by bre-fitzgerald**
# Pull Request/Issue Resolution

Closes #**BD-1261**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [ ] No

### CODE REVIEW

**Comment by bre-fitzgerald** [comment]
@johndinh Link to hidden page within deployment: https://braze-docs-en-git-bd-1261-braze.vercel.app/get_app_group_apps/

**Comment by johndinh** [comment]
@dringbraze and @emily-fong 

Adding y'all to this docs PR.

**Comment by johndinh** [comment]
LGTM

**Review by dringbraze — APPROVED** [review]
LGTM

**Pull request merged**
