### PR TITLE
Revert "SDK-1610 - updated kotlin android user calls"

### PR DESCRIPTION
**Pull request by radixdev**
Reverts braze-inc/braze-docs#2210

This is waiting for Android SDK 15.0.0 to be released.

### CODE REVIEW

**Comment by KellieHawks** [comment]
Hey @radixdev, 
Just confirming you don't want this merged today because of the "Do not merge" label.

**Comment by radixdev** [comment]
@KellieHawks yep, it's to wait until 15.0.0 is released. I think the PR macro didn't go through bc this was a revert commit PR.

**Comment by radixdev** [comment]
@KellieHawks ready to merge

**Review by KellieHawks — APPROVED** [review]
Looks great. Thanks!

**Pull request merged**
