### PR TITLE
add inbox monster partner doc and link to added page

### PR DESCRIPTION
**Pull request by laarnii**
### Summary

My PR adds the inbox monster partner page and links

### Related PRs, issues, or features (optional)

- N/A

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

### CODE REVIEW

**Comment by laarnii** [comment]
@braze-inc/docs-team, could I please get a site preview generated? Thank you

**Comment by josh-mccrowell-braze** [comment]
Hi @laarnii : Site preview generated! 

Please tag us in again when you're ready for us to review your updates!

**Comment by laarnii** [comment]
thank you. for the partners page, are we the one to add the icons/descriptions for our company icon to appear in the technology partners list or it is to be handled on your side?

**Comment by josh-mccrowell-braze** [comment]
@laarnii - Great question. That will be added on our side.

**Comment by laarnii** [comment]
@braze-inc/docs-team i am not sure if i am doing something wrong but i cannot select reviewers. thank you

**Comment by josh-mccrowell-braze** [comment]
Got it, @laarnii . We'll take it from here!

**Comment by laarnii** [comment]
> Got it, @laarnii . We'll take it from here!

thank you

**Comment by laarnii** [comment]
@braze-inc/docs-team, i was told to update a section and not sure if i need a new preview for that update. thank you

**Comment by josh-mccrowell-braze** [comment]
@laarnii : Went ahead and redeployed the preview!

**Comment by mpmpmpmp1** [comment]
Hi @josh-mccrowell-braze docs look good to me!

**Review by mpmpmpmp1 — APPROVED** [review]

**Review by rachel-feinberg — APPROVED** [review]

**Pull request merged**
