### PR TITLE
Update tv_and_ott.md for roku canvas support

### PR DESCRIPTION
**Pull request by chrisdp**
# Pull Request/Issue Resolution

#### Description of Change:
Updated the `Platforms and features` table to list Roku and unsupported for canvas.

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [x] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @internetisaiah as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Ana Teresa Serafino on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @internetisaiah for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@internetisaiah</td>
    <td>Developer Guide<br>Technology partners<br>Channels</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>Frontend Infrastructure & Experience (FIX)</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Comment by internetisaiah** [comment]
Hello @chrisdp , I'm a tech writer here at Braze. Thanks for contributing to Braze Docs!

Do you mind giving me a little more context to this change so I can help get it merged? Also, if you haven't yet already, be sure to [sign the CLA](https://www.braze.com/docs/cla/). If you have any questions, just ping me here.

Thanks!

**Comment by chrisdp** [comment]
Hey @internetisaiah 

This change is to mark the `Canvas` feature as not supported on the [following table](https://www.braze.com/docs/developer_guide/platform_integration_guides/tv_and_ott/#platforms-and-features):
image

As when you check the `Platform Integration Guides` this is not listed as a feature you can implement and it is also not mentioned in any of the change logs. As a result it is miss leading when evaluating the product. 
image

**Comment by internetisaiah** [comment]
Hello @chrisdp ,

Looks like the feature is supported for Roku as you can see in the following screenshot. That being said, that should be more clear in the docs. Thanks for raising this to us. I'll make a ticket to tackle this so it's more clear moving forward 👍🏽

image

**Comment by chrisdp** [comment]
@internetisaiah can you share the docs on how it would be implemented then as I don't see it listed.

**Comment by chrisdp** [comment]
@internetisaiah your showing the ui to set up in app messages. Not canvas.

**Comment by iObject** [comment]
@internetisaiah Your screenshot is referencing support for In-APp Messages, which is correct.  @chrisdp is asking to remove the Canvas support in the checklist, which is not supported on Roku,

**Comment by iObject** [comment]
@internetisaiah after reading through, I believe there was a misunderstanding of what "Canvas" was.

**Comment by internetisaiah** [comment]
Ah yes, Canvas is a UI component _in_ the Braze platform. It let's you set up campaigns with multiple messages and steps to create a custom customer journey (for more information, see [Canvas](https://www.braze.com/docs/user_guide/engagement_tools/canvas)). Once you pay for Braze (given you're on the appropriate plan), and [integrate the Roku SDK](https://www.braze.com/docs/developer_guide/platform_integration_guides/roku/initial_sdk_setup/), you and your team can use Canvas in the Braze platform to create custom campaigns for your customers.

Unlike Push Notifications, In-App Messages, etc. Canvas is _not_ something that is happening in your app or our SDK. Instead, Canvas is "happening" in the Braze platform.

I hope this clarification helps! Please let me know if you have any further questions 👍🏽 

@iObject @chrisdp

**Pull request closed without merging**
