### PR TITLE
ActionIQ and Airbyte Partnership Docs

### PR DESCRIPTION
**Pull request by KellieHawks**
@abelfort
Updated submitted documentation to align with other Braze documentation.
Your documentation will be added to the site once we get the go-ahead from our partnership team.
Please feel free to reach out if you have any issues.

Thanks,
The Braze Documentation Team

### CODE REVIEW

**Comment by abelfort** [comment]
@KellieHawks it seems like pieces of the ActionIQ document are missing. The doc in my original PR (https://github.com/braze-inc/braze-docs/pull/4858) is not the one that I'm seeing here. Please resolve this before uploading onto the Braze site.

**Review by bre-fitzgerald — APPROVED** [review]
lgtm!

**Comment by abelfort** [comment]
Hi @KellieHawks - it doesn't seem like the correct version/commit of my original PR was the one merged. Could you please review before publishing this doc on the website? https://github.com/braze-inc/braze-docs/pull/4858/files

**Comment by KellieHawks** [comment]
@abelfort Looking into this and will have it updated with our next deploy 3/7. Thanks for flagging. :)

**Comment by abelfort** [comment]
Thanks @KellieHawks, would you mind sharing the PR with the fix?

**Comment by KellieHawks** [comment]
@abelfort https://github.com/braze-inc/braze-docs/pull/4949

**Pull request merged**
