### PR TITLE
Brand refresh tweaks

### PR DESCRIPTION
**Pull request by zzhaobraze**
# Pull Request/Issue Resolution
Tweaks for brand refresh

### CODE REVIEW

**Comment by lydia-xie** [comment]
Pasting my comments from the Jira ticket:

Here are some minor things that I saw in the PR:

- Odd spacing issue between H2 and bullet list (might have to do with the padding from the title to the next item edit): https://braze-docs-6xj04ezxv-braze.vercel.app/docs/partners/message_orchestration/channel_extensions/email_templates/iam_studio/#prerequisites:~:text=of%20this%20partnership.-,Use%20cases,-Encouraging%20the%20purchase

- Similar odd spacing overlap between H2 and tabs: https://braze-docs-6xj04ezxv-braze.vercel.app/docs/partners/message_orchestration/channel_extensions/ecommerce/shopify/using_shopify/shopify_data_in_braze/?tab=example%20payload&subtab=product%20viewed&redirected=true#supported-shopify-events:~:text=and%20custom%20attributes.-,Supported%20Shopify%20events,-SHOPIFY%20EVENTS

- The first border radius for the Search input is 6px, but looks like the other 3 aren't (All Categories, All Specialities, All Solutions): https://braze-docs-6xj04ezxv-braze.vercel.app/docs/partners/home 

- And it looks like the links and punctuation starting a new line will have to be further investigated, but to echo Bre's comment, would it be possible to automatically add a non-breaking space between the end of a link if the next character is a period in the meantime?

**Review by lydia-xie — APPROVED** [review]
the changes lgtm! thank you for the help with this!

**Comment by zzhaobraze** [comment]
@lydia-xie feel free to merge this whenever unless you want me to merge.

**Comment by lydia-xie** [comment]
@zzhaobraze - The rest of the team is just giving this a final review right now, then I think @josh-mccrowell-braze will be merging it 🫡

**Review by josh-mccrowell-braze — APPROVED** [review]
Thanks @zzhaobraze !!

**Pull request merged**
