### PR TITLE
Update naming_convention.md

### PR DESCRIPTION
**Pull request by sambellbraze**
A few customers here in Australia have flagged that the Snowflake data schema references "user_id" which is actually the "braze_id" and "external_user_id" which is actually the "external_id". And said it's very confusing as no where does it explain what the "new" fields in the Snowflake data schema mean/map to. 

The Snowflake data schema page is being updated to explain the difference between the Snowflake data schema and the Braze data schema. And one of the customers who complained also highlighted this page as not even referencing the "external_id". 

Perhaps Braze is transitioning away from "external_id" however I wanted to propose this edit so that it's obvious to all customers that "external_user_id" also means "external_id"...

# Pull Request/Issue Resolution

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Comment by josh-mccrowell-braze** [comment]
Hi @sambellbraze Thanks for your patience with this one. 

Looking into this, this advice for assigning user ID names is used throughout the documentation. The clarification about the Snowflake naming conventions may be very useful for Snowflake users, but would be extraneous information for other users in all the contexts that this snippet is used. 

As such, I don't think this is the right way to add this clarification.

I hope that the clarification we added last week in the dedicated Snowflake article will help avoid the confusion your team faced. If you have other ideas on how to better get ahead of this issue in the future, please let me know!

**Comment by sambellbraze** [comment]
Hey @josh-mccrowell-braze 

The only reason why I suggested this edit (feel free to shut me down) is that in the docs (e.g. on this page: https://github.com/braze-inc/braze-docs/blob/edcad46aaab947664e8267a4e61d82453a852c36/_includes/archive/setting_user_ids/naming_convention.md?plain=1) it says "If you find your `external_user_ids` include names, email addresses, timestamps, or incrementors, we suggest using a new naming method that is more secure so that your user IDs are not as easy to guess or impersonate. If you choose to include this in your user IDs, ..."

In this sentence we have used "external_user_ids" (which I've only ever seen referenced in Snowflake, so seems out of character to use it for general Braze docs vs "user_id" or "external_id"), and then in the same sentence we use the word "user IDs". 

I agree the use of "user IDs" is completely fine. It was moreso the "external_user_id" being used which I've never seen on any other Braze docs pages (except now for the Snowflake page that has been updated which is now 100% clear thanks :))

**Comment by josh-mccrowell-braze** [comment]
Thank you so much for clarifying! I had glossed over that incongruity in my initial readthrough of your patch. Apologies. 

To my mind, this just feels like an _error_. We generally use this page when discussing the Braze naming conventions, and we're using the wrong parameter name. Let me follow up with Product about this. 

Thanks for bringing this to our attention (and making sure I actually got it).

**Comment by josh-mccrowell-braze** [comment]
@sambellbraze Just following up that after discussing with the SDK team I'm going to put in a patch that changes this language to talk about "user IDs" more generically/without code formatting. 

I think the nuance is that `external_user_id` is a parameter used in our APIs (and, thus, Snowflake). I hadn't understood that fully before now, so I'm glad I got my head around it.

Thanks again for bringing this to our attention.

**Comment by sambellbraze** [comment]
Completely fine @josh-mccrowell-braze 🙂

Yeh I've only ever seen this "external user id" used when snowflake is being referenced. I actually haven't seen it in any of our API docs yet. 

Thanks for looking to make a tweak!

**Pull request closed without merging**
