### PR TITLE
[SDK-3535] Add NCA code samples for iOS

### PR DESCRIPTION
**Pull request by hokstuff**
# Pull Request/Issue Resolution

#### Description of Change:
https://jira.braze.com/browse/SDK-3535

**Verified the code changes [in this branch off of Christopher's Swifty test branch](https://github.com/braze-inc/swift-sdk/compare/cbowns/nca/swifty-tests...cbowns/nca/swifty-tests__testCodeSamples?expand=1):**
- You will need to comment in / out code to test all of the commands.
- Then, you can verify on the Dashboard that each of the expected user custom attributes appear

Base branch: https://github.com/braze-inc/braze-docs/pull/5082

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [x] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Currents<br>Internal Tools<br>Product Partnerships<br>SMS<br>Customer Lifecycle, Identity and Permissions</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Intelligence<br>User Targeting<br>IAM<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging and Automation<br>Email (Composition and Infrastructure)</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Comment by bkasman95** [comment]
@hokstuff im not sure if it's a rendering issue but im only seeing the updates on the "Array of Objects" section and not the "Nested Custom Attributes" section

**Comment by hokstuff** [comment]
Ah, thanks - I need to add the appropriate snippets to that section as well!

**Comment by hokstuff** [comment]
This PR is [branched off this base branch](https://github.com/braze-inc/braze-docs/pull/5082) with adding NCA examples in each platform

I requested reviews for each of the authors to sanity check (though main review is for Christopher). We'll do another round in the base branch once all platforms are complete

**Review by cbowns — APPROVED** [review]
+1 looks great here!

**Comment by cbowns** [comment]
@bkasman95 <can of worms> did we want any of update/delete operator examples in the NCA doc, similar to the ones that are in "arrays of objects" atm?

**Comment by bryanlogan** [comment]
It feels like we're all a bit different in the examples.  For example, web will call the setCustomUserAttribute with the JSON object right in the call, Android will create the JSON object with the command and embedded JSONArray in a single var, and iOS will create the JSON Array, then the JSON Object, and then make the call.  

It's 6 of one, half dozen of the other, and....a day shy of a week's worth?  I dunno, maybe this is why they don't let it get to three.

**Comment by hokstuff** [comment]
> It feels like we're all a bit different in the examples. For example, web will call the setCustomUserAttribute with the JSON object right in the call, Android will create the JSON object with the command and embedded JSONArray in a single var, and iOS will create the JSON Array, then the JSON Object, and then make the call.

I guess in the end at least the logic is all basically the same. I think a decent compromise is to make the iOS side match the Android side, where instead of 2 variables (JSON array + JSON object), I can just introduce one new variable. I originally made that separate for easier readability, but it does make the example vary a bit.

It would be nice to have Web match up with 1 JSON variable and 1 `setCustomUserAttribute` call - but I think the JS code itself is easier to read (than e.g. the Android code of creating a JSON), so Web can have an all-in-one without too much confusion

**Comment by davidbielik** [comment]
> It feels like we're all a bit different in the examples. For example, web will call the setCustomUserAttribute with the JSON object right in the call, Android will create the JSON object with the command and embedded JSONArray in a single var, and iOS will create the JSON Array, then the JSON Object, and then make the call.
> 
> It's 6 of one, half dozen of the other, and....a day shy of a week's worth? I dunno, maybe this is why they don't let it get to three.

I can update web to match the others. we just don't typically write our code samples that way, but no reason it can't match.

**Comment by hokstuff** [comment]
Updated the iOS side as well to match with Android and (now) Web

Merging this to the base branch now

**Pull request merged**
