### PR TITLE
Removing developer nav

### PR DESCRIPTION
**Pull request by internetisaiah**
### Why are you making this change? (required)

The `developer_nav` is fairly unintuitive--mostly due to not being a standard feature on other tech-doc sites. Furthermore, this feature will be removed as a part of the #8078. Because of these reasons, we are opting to remove this feature now.

### Related PRs, issues, or features (optional)

- N/A

### Feature release date (optional)

- N/A

### Contributor checklist

- [x] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

### CODE REVIEW

**Comment by internetisaiah** [comment]
@zzhaobraze , i'm sure theres a much more elegant way to remove this, but i didn't know if this function was being called/used elsewhere. feel free to commit a better fix. thanks!

**Comment by zzhaobraze** [comment]
can delete this file and remove it from [_includes/html_include.html](https://github.com/braze-inc/braze-docs/blob/4b2c0e232f604d60bfba5f8204b668d7fba63a72/_includes/html_include.html#L96)

**Comment by internetisaiah** [comment]
@zzhaobraze , done ✅ . let me now if i removed the right line from `html_include.html`.

**Review by zzhaobraze — APPROVED** [review]
should be good but i'll just double check locally nothing breaks

**Comment by internetisaiah** [comment]
@zzhaobraze , no errors locally for me. gonna ship it 👍🏽

**Pull request merged**
