### PR TITLE
[SDK-1827] Update react_sdk_setup.md

### PR DESCRIPTION
**Pull request by bryanlogan**
# Pull Request/Issue Resolution

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (__Insert Feature Release Date Here__)
- [x ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [x ] Check that all links work.
- [x ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [x ] Tag @Timothy-Kim and @KellieHawks as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the chart below to tag the appropriate reviewer.
- [x ] Tag others as reviewers as necessary.
- [x ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24pl_DVxbu2T/pub)
- [Technical Documentation Style Guide](https://docs.google.com/document/d/e/2PACX-1vTtzHpcihaXTTYD85LoKIvYBvpCQFLr8n0BDKRDRAMEz_DnZdHJJINKL24r4JXkRUui24pl_DVxbu2T/pub#h.wstt3flbts5k)
- [Styling Test Page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_home/styling_test_page.md)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Heroku environment (click `View deployment` button below, then `Docs`, this can take up to 5 minutes to load. A `502` error means the deployment is still loading, refresh the page, and try again.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @timothy-kim or @KellieHawks for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@Timothy-Kim</td>
    <td>Application Infrastructure<br>Data Infrastructure</td>
  </tr>
  <tr>
    <td>@kelliehawks</td>
    <td>Intelligence<br>Product Partnerships<br>SMS<br>Internal Tools</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Reporting<br>Ingestion<br>Platforms and Channels<br>SMB</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Messaging and Automation<br>Dashboard Infrastructure<br>Email</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Review by radixdev — APPROVED** [review]

**Review by Bucimis — APPROVED** [review]

**Comment by Bucimis** [comment]
We should add a Kotlin version

**Comment by bryanlogan** [comment]
> We should add a Kotlin version

I think because we're already in a Android/IOS tab, I'm not sure we can have tabs within tabs.

**Comment by Bucimis** [comment]
Interesting, I think it's ok for now since the example is trivial. Ultimately we'll need to use some other way to separate Android/iOS if we can't nest tabs since both will need 2 languages for each code sample

**Comment by bre-fitzgerald** [comment]
> I think because we're already in an Android/IOS tab, I'm not sure we can have tabs within tabs.

Hey @bryanlogan and @Bucimis, you can use `subtabs` within a `tab`—the syntax is available on our [Styling Test Page](https://github.com/braze-inc/braze-docs/blob/develop/_docs/_home/styling_test_page.md). Hope that helps!

**Review by radixdev — APPROVED** [review]

**Review by Bucimis — APPROVED** [review]

**Comment by macolko** [comment]
@Bucimis I was wondering if there were actually cases where React Native is built/bridged on top of Kotlin? It normally supports only Java/Obj C. If that's the case, would it also be helpful to add Swift?

**Comment by bryanlogan** [comment]
> @Bucimis I was wondering if there were actually cases where React Native is built/bridged on top of Kotlin? It normally supports only Java/Obj C. If that's the case, would it also be helpful to add Swift?

Any app that's pure RN, the developers probably won't touch the boilerplate native code which is going to be Java.  They could be writing an app that's Kotlin/RN, but they're probably doing advanced enough stuff this wouldn't apply.

With that said, I don't think there's harm in leaving the Kotlin there, and probably no rush to get Swift, but I'll leave that up to the iOS team.

**Review by macolko — APPROVED** [review]

**Review by KellieHawks — APPROVED** [review]
Lgtm!

**Review by chshapiro — COMMENTED** [review]
lgtm!

**Comment by Bucimis** [comment]
@macolko Sorry for chiming in late here, as Bryan mentioned, the default templates are in Obj-c/Java but developers can and do write the majority of the native side in Swift/Kotlin. On Swift they'd need to set up bridging and for Kotlin they'd need to make sure kotlin support libraries are included.

Here's an example of a RN codebase that incorporates Swift and Kotlin https://github.com/stripe/stripe-react-native/tree/master/ios

**Comment by macolko** [comment]
@Bucimis @bryanlogan That makes a lot of sense. I agree there is no reason not to include the Kotlin snippets. Thanks so much for your input!

**Pull request merged**
