### PR TITLE
File in-app_messages.md committed.

### PR DESCRIPTION
**Pull request by Translationmanagement**

### CODE REVIEW

**Comment by iaraltkorn** [comment]
@braze-inc/docs-team ready to merge

**Review by josh-mccrowell-braze — APPROVED** [review]

**Comment by josh-mccrowell-braze** [comment]
@cla-bot check

**Comment by josh-mccrowell-braze** [comment]
@cla-bot check

**Comment by josh-mccrowell-braze** [comment]
@cla-bot check

**Comment by lydia-xie** [comment]
@cla-bot check

**Comment by iaraltkorn** [comment]
@braze-inc/docs-team added a few files to the PR - we can merge everything :)

**Pull request merged**
