### PR TITLE
Swift v7.0.0 UUID 

### PR DESCRIPTION
**Pull request by bkasman95**
pending changes for Swift SDK v7.0.0 release

### CODE REVIEW

**Review by jerielng — APPROVED** [review]
LGTM

**Review by jacksonemiller — APPROVED** [review]

**Comment by bkasman95** [comment]
@jerielng the edits in the current docs seem incomplete compared to the edits here with the mentioning of this being enabled by default and removing the flow chart and mentioning of v5.7.0. id prefer to use these if you guys are ok with it

**Comment by jerielng** [comment]
> @jerielng the edits in the current docs seem incomplete compared to the edits here with the mentioning of this being enabled by default and removing the flow chart and mentioning of v5.7.0. id prefer to use these if you guys are ok with it

Gotcha, yea that sounds good. Thanks for the heads up!

**Comment by hokstuff** [comment]
🔥🔥🔥

Looks good, I think we just need to resolve conflicts

**Comment by bkasman95** [comment]
@josh-mccrowell-braze can we get this reviewed and merged?

**Pull request merged**
