### PR TITLE
React navigation updates to documentation

### PR DESCRIPTION
**Pull request by bre-fitzgerald**
# Pull Request/Issue Resolution

### CODE REVIEW

**Review by josh-mccrowell-braze — APPROVED** [review]
I read through the developer docs and the hidden docs sections. Those sections look good! Thanks for this big lift.

**Comment by bre-fitzgerald** [comment]
@cla-bot check

**Review by lydia-xie — APPROVED** [review]
lgtm! great work :)

**Comment by lydia-xie** [comment]
@cla-bot check

**Comment by lydia-xie** [comment]
@cla-bot check

**Review by KellieHawks — APPROVED** [review]
Looks great!!

**Pull request merged**
