### PR TITLE
Replace securiti.ai with onetrust

### PR DESCRIPTION
**Pull request by zzhaobraze**
# Pull Request/Issue Resolution
Replace secruriti.ai with onetrust

### CODE REVIEW

**Review by CaitlinWeb — CHANGES_REQUESTED** [review]
This is looking good, thanks for putting it together so fast! Banner and footer link is correct. Last thing that's needed is the [Google Consent Mode script](https://docs.google.com/document/d/1Pm_BomwFG17W90YBJgs1MX6gogFkDJcIxS7N59Vcqgk/edit#heading=h.tem4tg40yobx). 

Also noting that before this can be deployed I'll have to test Google Tag Manager changes (which I can use the preview URL for). Once that's looking good we'll need to coordinate deploying this at the same time as publishing the Docs site's GTM container. Unless you feel like you could handle that, and I could support as needed. Can give you permissions for the GTM container (which I probably should anyway), just let me know.

**Comment by josh-mccrowell-braze** [comment]
Hey there @zzhaobraze . Just checking in about the status of this one. Let me know if I can help!

**Comment by zzhaobraze** [comment]
@josh-mccrowell-braze  waiting on @CaitlinWeb to confirm if everything looks good.

**Review by CaitlinWeb — APPROVED** [review]
Looks good to me for OneTrust implementation! Also tested with Google Tag Manager (used browser override to use the test version of the banner for testing functionality dependent on domain); those changes are good to go as well. 

I did notice there's one piece of SecuritiAi cleanup not completed, tho:
__includes/html_include.html_: line 49
`<link type="text/css" rel="stylesheet" href="https://cdn-prod.securiti.ai/consent/cookie-consent.css" />`

**Comment by zzhaobraze** [comment]
> html_include

thanks for noticing. removed also

**Comment by zzhaobraze** [comment]
@josh-mccrowell-braze feel free to merge when ready

**Pull request merged**
