### PR TITLE
[DLK-1447] Update User Deletes docs to talk about integration type

### PR DESCRIPTION
**Pull request by andrewcarlberg**
# Pull Request/Issue Resolution

#### Description of Change:
Adding notes about the data type needed for the sync type for user deletes

Closes https://jira.braze.com/browse/DLK-1447

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [x] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [x] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [x] Check that all links work.
- [x] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [x] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [x] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Review by colleenkerr — APPROVED** [review]

**Review by josh-mccrowell-braze — CHANGES_REQUESTED** [review]
Hi @colleenkerr 

I gave this page a little TLC beyond this change. Would you please re-review in general for my edits? 

Hi @andrewcarlberg 

For consistency with our image style guide, we should not include a red box or highlight the screenshot. Would you please provide an updated screenshot without this element? I'm happy to take the screenshot as well, but don't know an environment with an existing Snowflake integration I can use to take it. If you get me these details, I'd be happy to take a screenshot instead.

Let me know if you have any questions. Thanks!

**Comment by josh-mccrowell-braze** [comment]
@andrewcarlberg : No, the highlighting from the UI itself is fine. I just meant added highlighting from image capture software. The new picture is perfect. Thank you!

**Comment by andrewcarlberg** [comment]
@josh-mccrowell-braze I updated the asset.  @colleenkerr is out this week.

**Comment by josh-mccrowell-braze** [comment]
Thanks @andrewcarlberg! If I waited to merge this until @colleenkerr reviewed, does that hurt the timeline for your ticket or would that be acceptable?

**Comment by andrewcarlberg** [comment]
I have a ticket for it I would like to be done this sprint (Wednesday)

**Comment by josh-mccrowell-braze** [comment]
Understood. Merging now and following up with Colleen when she returns for her feedback.

**Review by josh-mccrowell-braze — APPROVED** [review]

**Pull request merged**
