### PR TITLE
Docs Feature: Last Modified Date

### PR DESCRIPTION
**Pull request by internetisaiah**
# Pull Request/Issue Resolution

#### Description of Change:

This is a demo of the [jekyll-last-modified-at](https://github.com/gjtorikian/jekyll-last-modified-at) plugin that shows the date the page was last modified. For demo purposes, I placed the date `<div>` above the content title, but this can be placed anywhere using standard Liquid syntax.

- [Figjam Mockups](https://www.figma.com/file/dANMToEHgLVgGt2pefEfe2/Last-Updated-Voting?type=whiteboard&node-id=0%3A1&t=o0wyPFdMLxKFoSc2-1)

#### TODO

- [x] Remove the manually-added "Last updated" text in the Help section (and other locations if applicable).
- [x] Update text size to align with other nav text. 
    - Other navigational text, like "Home" is 13px. This text is 16 px.
- [ ] Verify how language translation is handled in reference to the `%B` variable. Relevant docs: [Liquid date](https://shopify.github.io/liquid/filters/date/).
    - We can also consider avoiding this situation entirely by using a non-language based date format. _However_, I believe Europe does `dd-mm-yy` rather than US-standard `mm-dd-yy`.

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [x] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @internetisaiah as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @internetisaiah for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@internetisaiah</td>
    <td>Developer Guide<br>Technology partners<br>Channels</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>Frontend Infrastructure & Experience (FIX)</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Comment by internetisaiah** [comment]
Hey @zzhaobraze , this one is ready for some eyes when you get the chance! Could you also help me with my last TODO item above? (Making sure the Month name is properly translated for non-english-speaking countries?).

Let me know if you have any questions!

**Comment by zzhaobraze** [comment]
> **Potential bug:** all docs are getting flagged as "March 1, 2024." Verify whether this is an issue with:
> 
> * The plugin
> * My implementation
> * How vercel handles fetching data from Git for site previews
> 
> **Update:**
> 
> This is _likely_ due to Vercel as all the dates are different/unique in my local environment. Verify with engineering.


This will probably not work well as you noticed. When vercel pulls the git repo, it looks to reset this date, so this last modified date won't be accurate. I had similar issues when trying to use the git commit date to update the last modified date.

**Comment by zzhaobraze** [comment]
Here's the test PR if you're interested https://github.com/braze-inc/braze-docs/pull/4451/files

**Comment by internetisaiah** [comment]
> Here's the test PR if you're interested https://github.com/braze-inc/braze-docs/pull/4451/files

Hmm, interesting 🤔 Is there anyway to update the build pipeline to not do this? Or will it break other things? Or perhaps even drastically decrease site performance?

**Pull request closed without merging**
