### PR TITLE
[SDK Untracked] Update Appsflyer integration code snippet

### PR DESCRIPTION
**Pull request by jacksonemiller**
### Summary

Relevant page: https://braze-docs-j2admcsrq-braze.vercel.app/docs/partners/message_orchestration/attribution/appsflyer/appsflyer/?tab=swift

Follow up to [this support issue](https://servicedesk.braze.com/browse/PQ-3781). The `deviceId` method used in these code snippets [was deprecated in 5.13.0](https://github.com/braze-inc/braze-swift-sdk/releases/tag/5.13.0).

### Contributor checklist

- [x] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

### CODE REVIEW

**Review by Bucimis — APPROVED** [review]

**Review by vanessaland — APPROVED** [review]

**Review by jerielng — APPROVED** [review]
Swift portion LGTM

**Review by jerielng — CHANGES_REQUESTED** [review]
Do we need to update the Objective-C portion as well?
```objc
BRZConfiguration *configurations = [[BRZConfiguration alloc] initWithApiKey:@"BRAZE_API_KEY" endpoint:@"BRAZE_END_POINT"];
[configurations setUseUUIDAsDeviceId:NO];
Braze *braze = [[Braze alloc] initWithConfiguration:configurations];
[braze deviceIdWithCompletion:^(NSString * _Nonnull brazeDeviceId) {
    NSLog(@">>[BRZ]: %@", brazeDeviceId);
    [[AppsFlyerLib shared] setAdditionalData:@{
        @"brazeDeviceId": brazeDeviceId
    }];
}];
```

I believe the `deviceIdWithCompletion` method is deprecated in favor of just the `deviceId` variable.

While we're at it, could we also swap the order of the Obj-C and Swift tabs so that Swift appears first as the default?

**Review by jerielng — APPROVED** [review]

**Comment by josh-mccrowell-braze** [comment]
Hi @jacksonemiller : Just let us know when this one is ready for techwriter approval!

**Review by hokstuff — APPROVED** [review]
LGTM after swapping the order to make the Swift tab the default

This is what I see from the deployment still with ObjC as the default:
Screenshot 2024-08-06 at 4 08 47 PM

**Comment by jacksonemiller** [comment]
Ready for your review @internetisaiah.

**Review by internetisaiah — APPROVED** [review]
LGMT

**Comment by internetisaiah** [comment]
This one's good to go @jacksonemiller . Ready to merge?

**Comment by jacksonemiller** [comment]
> This one's good to go @jacksonemiller . Ready to merge?

Yep. Thanks!

**Pull request merged**
