### PR TITLE
Scuba Analytics - Partner Docs

### PR DESCRIPTION
**Pull request by scuba-tptns**
# Pull Request

@josh-mccrowell-braze @bre-fitzgerald @alex-braze 

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ x] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ x] Check that all links work.
- [ x] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ x] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ x] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Review by alex-braze — CHANGES_REQUESTED** [review]
Hey @scuba-tptns can we get a couple of clarifications added to the docs?
- Is the `_update_existing_only` included in the payload, if so it it set to true or false?
- How are customers usually triggering the exports. Postman, or…
- Is batching and rate limiting being respected?

**Review by alex-braze — APPROVED** [review]

**Comment by internetisaiah** [comment]
Hello @scuba-tptns,

Thanks for contributing to Braze Docs! My name is Isaiah and I'm a member of the docs team here at Braze. I'll be here to help you get your PR reviewed and merged as soon as possible.

In the meantime, can you please complete the following:

1. Open and review the [Contribution License Agreement](https://www.braze.com/docs/cla/) form.
2. Scroll to the bottom of the page and fill out the following:
    - **Name ("You"):** Your first and last name.
    - **Signature:** Your first and last name (which will be used as your e-signiature)
    - **GitHub Username:** Your GitHub Username (which is @lauren-stein)
    - **Email:** Your email address [associated with your GitHub account](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/adding-an-email-address-to-your-github-account).
    - **Address:** Your physical address.
    - **Company Name:** (If applicable) the name of your employer.
    - **By:** (If applicable) your first and last name.
    - **Title:** (If applicable) your job title.

Let me know if you have any questions!

**Comment by bre-fitzgerald** [comment]
@cla-bot check

**Comment by internetisaiah** [comment]
Hi @scuba-tptns , hope you're doing well today! When you get the chance, can you check the information posted above:
https://github.com/braze-inc/braze-docs/pull/6477#issuecomment-1883973092

I see that you successfully signed the CLA, but there appears to be a misalignment with the local vs. registered email.

When you're finished with these steps, could you let me know? Thanks in advance!

**Comment by internetisaiah** [comment]
Hi @scuba-tptns,

To get your changes merged as soon as possible, I'm going to create a new PR with your commits and review them. I'll tag you in the new PR once I've pushed it to the repo. Thanks for your patience!

**Comment by internetisaiah** [comment]
Hey @scuba-tptns ,

Here's the new PR:

https://github.com/braze-inc/braze-docs/pull/6721

I'm reviewing your work now 👍🏽

**Pull request closed without merging**
