### PR TITLE
BD-1762: Broken links in note and tabs

### PR DESCRIPTION
**Pull request by bre-fitzgerald**
# Pull Request/Issue Resolution

Closes #**BD-1762**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

### CODE REVIEW

**Review by josh-mccrowell-braze — APPROVED** [review]
Learning that footnote-style links don't work in the alerts. Good to know! Thank you!

**Comment by davidbielik** [comment]
hey @bre-fitzgerald any way the tabs component can be fixed to support this?

**Comment by bre-fitzgerald** [comment]
> hey @bre-fitzgerald any way the tabs component can be fixed to support this?

@davidbielik as far as I know this is a limitation with Liquid, but @zzhaobraze or @KellieHawks feel free to chime in.

**Comment by zzhaobraze** [comment]
@davidbielik are you referring to passing in the [#] link within the custom alerts liquid tag? That's unfortunately an issue with how the custom liquid works. When parse the content, it doesn't have any reference to information outside the custom liquid. I'll double check if it's something that can be fixed and will let you know if it's doable.

**Pull request merged**
