### PR TITLE
Update security_settings.md

### PR DESCRIPTION
**Pull request by sambellbraze**
Under the "## Downloading a security event report" heading, are we able to list out a more extensive list of what exactly is able to be downloaded from this report? Often customers ask, but we have no long list of event types that are include in this report... so updating the docs would be very helpful please.

### Summary

My PR...

### Related PRs, issues, or features (optional)

- N/A

### Feature release date (optional)

- N/A

### Contributor checklist

- [ ] I confirm that my PR meets the following:
    - I signed the [Contribution License Agreement (CLA)](https://www.braze.com/docs/cla).
    - My style and voice follows the [Braze Style Guide](https://docs.google.com/document/u/2/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub).
    - My content contains correct spelling and grammar.
    - All links are working correctly.
    - If I renamed or moved a file or directory, I set up [URL redirects](https://www.braze.com/docs/contributing/content_management/redirecting_urls) for each file.
    - If I updated or replaced an image, I did not remove the original image file from the repository. (For more information, see [Updating an image](https://www.braze.com/docs/contributing/content_management/images/#updating-an-image)).
    - If my PR is related to a paid SKU, third party, SMS, AI, or privacy, I have received written approval from Braze Legal.

### Submitting for review

If your PR meets the above requirements, select **Ready for review**, then add a reviewer:
- **Non-Braze contributors:** Add `braze-inc/docs-team` as the reviewer.
- **Braze employees:** Have any relevant subject matter experts (like engineers or product managers) review your work first, then add the [tech writer assigned to your specific vertical](https://confluence.braze.com/pages/viewpage.action?pageId=75039896). If you're not sure which tech writer to add, you can add `braze-inc/docs-team` instead. 

Thanks for contributing! We look forward to reading your work.

### CODE REVIEW

**Comment by josh-mccrowell-braze** [comment]
Hi @sambellbraze 

I really appreciate your continued work to make sure the docs are up to date and working well!

When you have a suggestion for an opportunity for improvement that asks the team to do some research, like in this PR, it would be better to open this as a [Doc Request ](https://www.braze.com/docs/request). This will let us assign the work and track it as a task.

I went ahead and submitted these requests on your behalf for this PR and another that you recently opened:
* https://jira.braze.com/browse/BD-3445
* https://jira.braze.com/browse/BD-3446

I'll go ahead and close this PR, but you can track our progress on your suggestions through those Jira tasks. Let me know if you have any questions!

Thanks so much for your hard work in helping keep our documentation up to date!

**Comment by sambellbraze** [comment]
Hey Josh,

Not an issue at all. I greatly appreciate that the team most often approves
my changes, and actions them so quickly!

Should I submit every single docs request via that form? Would that make
things even easier/follow the correct process?


Cheers,

Andrew

_________


Andrew Sambell | Manager, Customer Success | Braze | 100 William St, Sydney
NSW 2011 | +61 421 725 012
----
Certified and Accredited: Standard Mental Health First Aider after
successful completion of the Standard MHFA course and assessment.

**Comment by sambellbraze** [comment]
Ok yep - that all makes sense. Can do!

It'll be a bit quiet from me for the next 4mths as I'm going on paternity
leave, but I'll be sure to keep up my contributions in 2025! ;)


Cheers,

Andrew

_________


Andrew Sambell | Manager, Customer Success | Braze | 100 William St, Sydney
NSW 2011 | +61 421 725 012
----
Certified and Accredited: Standard Mental Health First Aider after
successful completion of the Standard MHFA course and assessment.

**Comment by josh-mccrowell-braze** [comment]
Andrew,

Oh my gosh, congratulations! 
I'll look forward to your return, but hope you have a good paternity leave!

Cheers,
Josh

**Comment by sambellbraze** [comment]
Thanks :)


Andrew

_________


Andrew Sambell | Manager, Customer Success | Braze | 100 William St, Sydney
NSW 2011 | +61 421 725 012
----
Certified and Accredited: Standard Mental Health First Aider after
successful completion of the Standard MHFA course and assessment.

**Pull request closed without merging**
