### PR TITLE
Update ssl.md

### PR DESCRIPTION
**Pull request by sambellbraze**
I am nearly 100% sure that this step "Reach out to your customer success manager to get SSL turned on." in setting up an SSL cert is incorrect. 

Once the customer has setup their SSL certificate themselves, pointing the DNS to their CDN, they are good to go so I feel this step should be removed. 

Maybe check with Email Ops, but I am nearly 100% confident in this as I've never had to validate a customers SSL setup once it's locked in.

# Pull Request/Issue Resolution

Closes #**ISSUE_NUMBER_HERE**

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [ ] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [ ] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [ ] Check that all links work.
- [ ] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [ ] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [ ] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure) (tag @rachel-feinberg for Liquid use cases)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Comment by tiffanyjlin** [comment]
After the customer sets up SSL on their end, there is a final step where the COM or CSM has to check the 'SSL Enabled' checkbox in Internal Tools (see Step 10 on this page: https://confluence.braze.com/display/ONIT/SparkPost#SparkPost-Testemailfromthecustomerdashboard)

We could say something like 'Once you've set up SSL/completed the above steps, reach out to your customer success manager to ensure SSL engagement tracking is enabled in your email setup'

**Comment by sambellbraze** [comment]
> After the customer sets up SSL on their end, there is a final step where the COM or CSM has to check the 'SSL Enabled' checkbox in Internal Tools (see Step 10 on this page: https://confluence.braze.com/display/ONIT/SparkPost#SparkPost-Testemailfromthecustomerdashboard)
> 
> We could say something like 'Once you've set up SSL/completed the above steps, reach out to your customer success manager to ensure SSL engagement tracking is enabled in your email setup'

Ah!
I think this is ONLY for Sparkpost customers. Here in Australia every single customer is a SendGrid customer. And in that Confl page it doesn't mention SendGrid anywhere... potentially this is why we've never had to do that final step here in Australia?

If there is a nuance for Sparkpost vs Sendgrid, can this maybe be mentioned in that final step? "For customers who have been setup on our Sparkpost Email infrastructure, reach out to your CSM to validate your SSL. For customers who have been setup on our Sendgrid Email infrastructure, there is no further action required"... or something like that??

**Comment by tiffanyjlin** [comment]
@sambellbraze it also applies for Sendgrid (see the step to create a ticket with Email Ops on this page: https://confluence.braze.com/display/ONIT/SendGrid#SendGrid-Testemailfromthecustomerdashboard), as they have a similar flag to enable

**Comment by sambellbraze** [comment]
This is very strange @tiffanyjlin - I've just asked my other CSM colleagues if they've ever done this step. 
I've had dozens of customers buy new IPs and set them up and I've never done this step, nor had Email Ops tell me it's a step/that I forgot to do it.

Let me come back to you on this!

**Comment by sambellbraze** [comment]
@tiffanyjlin appreciate you sharing the Confluence link - my team have said they heard about these changes in Q4 as well - so seems I missed that update re SendGrid. Apologies for any confusion (more so on my side!).

Happy for my request to be deleted.

**Comment by josh-mccrowell-braze** [comment]
@sambellbraze Thanks for raising the issue! @tiffanyjlin Thanks for providing clarification!

**Pull request closed without merging**
