### PR TITLE
Antavo Loyalty Cloud - Partner Docs

### PR DESCRIPTION
**Pull request by andrasAntavo**
Committer: Andras Antavo <andras.taraszovics@antavo.com>

# Pull Request/Issue Resolution

CC @josh-mccrowell-braze @bre-fitzgerald

Please reach out to Tibor Tasi (tibor.tasi@antavo.com) and Gabor Vigh (gabor.vigh@antavo.com) for details.

#### Is this change associated with a Braze feature/product release?
- [ ] Yes (**Insert Feature Release Date Here**)
- [X] No

---

<details>
<summary>✔️ Pull Request Checklist</summary>
<br>

- [X] Check that you haven't removed any images (replacing an image with an updated one of the same name is fine), as this breaks the French site
- [X] Check that all links work.
- [X] Ensure you have completed [our Contributors License Agreement](https://www.braze.com/docs/cla/).
- [X] Tag @josh-mccrowell-braze and @bre-fitzgerald as a reviewer when your work is **done and ready to be reviewed for merge**. Are you an internal product manager? Reference the internal reviewing chart to tag the appropriate reviewer.
- [ ] If the documentation involves a 1) paid SKU, 2) a third party, 3) SMS, 4) AI, or 5) privacy, ensure that Maria Maldonado on the Legal team has signed off.
- [X] Tag others as reviewers as necessary.
- [ ] If you have modified any links, be sure to add redirects to `assets` > `js` > `broken_redirect_list.js`

</details>

<details>
<summary>⭐ Helpful Wiki Shortcuts</summary>
<br>

- [Writing Style Guide](https://docs.google.com/document/d/e/2PACX-1vTluyDFO3ZEV7V6VvhXE4As_hSFwmnFFdU9g6_TrAYTgH1QmbRoEDDdn5GzKAB9vdBbIdyiFdoaJcNk/pub)
- [Image Style Guide](https://docs.google.com/document/d/e/2PACX-1vRJSkwcjmjrTfLDagZccLpOMMyh5NN5SXRZSjz12cRAHbX4OrUmhvCmYpf_p5YB-9r4_jSOQLkicQIH/pub)
- [Styling Test Page](https://www.braze.com/docs/home/styling_test_page/)

</details>

<details>
<summary>❗ ATTN: For PR Reviewers</summary>
<br>

- [ ] Read our [Reviewing a PR page](https://github.com/Appboy/braze-docs/wiki/Reviewing-a-PR) for more on our reviewing suggestions.
- [ ] Read our [Previewing Documentation page](https://github.com/braze-inc/braze-docs/wiki/Previewing-and-Testing-Documentation) to see how to check the deployment.
  - [ ] Preview all changes in the linked Vercel environment by clicking the preview link in the vercel-bot comment in your PR.
</details>

<details>
<summary>❗ ATTN: Internal Reviewing Chart </summary>
<br>
<b>Work at Braze and not sure who to tag for review?</b> <br>Before tagging @josh-mccrowell-braze or @bre-fitzgerald for a general review, reference the following chart to see if a specific product vertical/reviewer applies to your pull request.
<br><br>
<table>
<tr>
    <td><b>Reviewer</b></td>
    <td><b>Product Vertical</b></td>
  </tr>
  <tr>
    <td>@josh-mccrowell-braze</td>
    <td>Monolith Deployments<br>Quality Infrastructure<br>Platform Infrastructure<br>Datalake<br>SDKs<br>Currents</td>
  </tr>
  <tr>
    <td>@bre-fitzgerald</td>
    <td>Intelligence<br>In-App Messages<br>Channels<br>FIX</td>
  </tr>
  <tr>
    <td>@lydia-xie</td>
    <td>Ingestion<br>Core Objects<br>Core Messaging<br>Messaging Experience<br>Message Components<br>Email (Composition and Infrastructure)</td>
  </tr>
  <tr>
    <td>@rachel-feinberg</td>
    <td>Customer Lifecycle, Identity and Permissions<br>SMS<br>User Targeting<br>Reporting</td>
  </tr>
</table>
</details>

### CODE REVIEW

**Comment by alex-braze** [comment]
Hey @andrasAntavo thanks for submitting these! After doing a review there were a couple of questions we have and these often get asked by customers. Could you answer or address these in the docs?

**Data Points**
Braze runs on data point consumption model and therefore we recommend only sending in attributes when those values have changed. ([Our docs for reference](https://www.braze.com/docs/user_guide/data_and_analytics/data_points#data-points))
1. Can you confirm whether it is possible to set up the workflows in such a way that, once synced the first time, will only trigger further syncs when that value has been updated?
2. If so, can you provide an example in the docs of how to do that?

**Data Types**
- What attribute data types are supported by the integration?
- What event property data types are supported by the integration?

**Purchases**
Are purchase events supported?

**User Identifiers**
What identifiers does Antavo support syncing to (e.g. external_id, user_alias, etc)

**Comment by andrasAntavo** [comment]
> Hey @andrasAntavo thanks for submitting these! After doing a review there were a couple of questions we have and these often get asked by customers. Could you answer or address these in the docs?
> 
> **Data Points** Braze runs on data point consumption model and therefore we recommend only sending in attributes when those values have changed. ([Our docs for reference](https://www.braze.com/docs/user_guide/data_and_analytics/data_points#data-points))
> 
> 1. Can you confirm whether it is possible to set up the workflows in such a way that, once synced the first time, will only trigger further syncs when that value has been updated?
> 2. If so, can you provide an example in the docs of how to do that?
> 
> **Data Types**
> 
> * What attribute data types are supported by the integration?
> * What event property data types are supported by the integration?
> 
> **Purchases** Are purchase events supported?
> 
> **User Identifiers** What identifiers does Antavo support syncing to (e.g. external_id, user_alias, etc)

Hello @alex-braze, thanks for the feedback! We have applied the necessary changes and pushed a new version, can you please review?

**Review by alex-braze — APPROVED** [review]

**Comment by bre-fitzgerald** [comment]
@cla-bot check

**Comment by bre-fitzgerald** [comment]
Hi @andrasAntavo. I understand this documentation is aiming to go live before 8/25, however, please be advised that we will **not** be able to merge your PR until the issue with your GitHub identity has been resolved. Please follow the steps above at your earliest convenience. Thanks!

cc: @alex-braze @josh-mccrowell-braze

**Comment by andrasAntavo** [comment]
> Hi @andrasAntavo. I understand this documentation is aiming to go live before 8/25, however, please be advised that we will **not** be able to merge your PR until the issue with your GitHub identity has been resolved. Please follow the steps above at your earliest convenience. Thanks!
> 
> cc: @alex-braze @josh-mccrowell-braze

@bre-fitzgerald thanks for the reminder. I actually ran these commands and found that the settings are correct. I believe the initial commit could have been with the wrong user alias and the rest should be fine. Should I try to fix the initial commit? If that's the case, should you give me a pointer on which command to run to fix them?

**Comment by zzhaobraze** [comment]
> identity

hi @andrasAntavo did you make your changes with git cli? or github.com ? if you were using the cli, can you try making a minor edit and pushing your change to see if github picked up the new settings?

Thanks

**Comment by andrasAntavo** [comment]
Hello @zzhaobraze, I tried to rebase the commit which had the wrong author but it seems something got broken in the process after pulling the original repository and merging it (even though I started the rebase right from the commit which I wanted to change). I will ask for help from my teams tomorrow (European time) to fix this as it seems that the original commit is still there and the rebase was unsuccessful.

**Comment by zzhaobraze** [comment]
@andrasAntavo would it be easier/faster to just close this PR, and you can make a new Fork of the repo with the changes to resubmit?

**Comment by andrasAntavo** [comment]
> @andrasAntavo would it be easier/faster to just close this PR, and you can make a new Fork of the repo with the changes to resubmit?

@zzhaobraze  Yes, will try this soon. Thanks!

**Comment by andrasAntavo** [comment]
Closing this PR as there will be a new one created with the changes.

**Pull request closed without merging**
